platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'SDKExample' do
  pod 'Drift', :path => '../../Drift.podspec'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['Alamofire', 'AlamofireImage'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
